### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by iam4x** [savemysmartphone/universal-redux-boilerplate#2]
- [ ] Wait for react-router@1.0
- [x] Wait for redux@1.0
- [x] Add react-intl ~~(other i18n implementation?)~~
- [x] Add localized routes
- [ ] Add tests
- [ ] Add documentation
- [ ] Add auth / login example
- [x] Refactor webpack config

**Comment by dmitry** [comment]
@iam4x can you in short compare https://github.com/iam4x/isomorphic-flux-boilerplate/ and https://github.com/savemysmartphone/universal-redux-boilerplate/? I believe the only main difference is a flux libraries: alt and redux. From your experience, what is the most easy to use (docs/read code/etc) and powerful (featureful and perspective)?

**Comment by iam4x** [comment]
Redux is getting really popular, I think it will be one of he most used Flux library and @gaearon is getting funded for working on it (http://patreon.com/reactdx) so I gave it a shot.

Alt isn't moving fast enough, the community not growing as fast as Redux and I'm waiting for the server side render PR for a month or more (I don't have enough time to help them on this I have already open source projects to care of myself).

Another difference is, expressjs as koajs replacement (with async / await keywords no need of genereators and yield keyword, and it's much easier to route an API on the same server https://github.com/savemysmartphone/universal-redux-boilerplate/blob/master/server%2Fexpress.js#L53)

**Comment by dmitry** [comment]
@iam4x thanks for noticing all the main points. That's really helpful. 

Hopefully, I will find a time to rework current project into a redux/express, because for me it seems reasonable.
